export const products = [
  {
    id: '1',
    title: 'Fresh Organic Tomatoes',
    price: '₹30/kg',
    quantity: '500 kg',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400',
    location: 'Fatehabad, Haryana',
    seller: 'Rajinder Kumar',
    categoryPath: ['Vegetables', 'Tomato'],
  },
  {
    id: '2',
    title: 'Premium Basmati Rice',
    price: '₹85/kg',
    quantity: '2000 kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    location: 'Karnal, Haryana',
    seller: 'Suresh Singh',
    categoryPath: ['Crops', 'Rice'],
  },
  {
    id: '3',
    title: 'Alphonso Mangoes',
    price: '₹120/kg',
    quantity: '300 kg',
    image: 'https://images.unsplash.com/photo-1605027990121-cbae9e0642df?w=400',
    location: 'Ratnagiri, Maharashtra',
    seller: 'Amit Patil',
    categoryPath: ['Fruits', 'Mango'],
  },
  {
    id: '4',
    title: 'Fresh Farm Potatoes',
    price: '₹20/kg',
    quantity: '1500 kg',
    image: 'https://images.unsplash.com/photo-1518977676601-b53cf82aba33?w=400',
    location: 'Agra, Uttar Pradesh',
    seller: 'Mahesh Yadav',
    categoryPath: ['Vegetables', 'Potato'],
  },
  {
    id: '5',
    title: 'Organic Wheat Grains',
    price: '₹28/kg',
    quantity: '5000 kg',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
    location: 'Bathinda, Punjab',
    seller: 'Gurpreet Singh',
    categoryPath: ['Crops', 'Wheat'],
  },
  {
    id: '6',
    title: 'Pure Desi Cow Ghee',
    price: '₹650/litre',
    quantity: '50 litre',
    image: 'https://images.unsplash.com/photo-1628065824634-1de85fd67b1e?w=400',
    location: 'Nashik, Maharashtra',
    seller: 'Sunita Devi',
    categoryPath: ['Dairy Products', 'Ghee'],
  },
  {
    id: '7',
    title: 'Red Onions - Bulk',
    price: '₹18/kg',
    quantity: '3000 kg',
    image: 'https://images.unsplash.com/photo-1620574387735-3624f7f1a15e?w=400',
    location: 'Lasalgaon, Maharashtra',
    seller: 'Prakash Jadhav',
    categoryPath: ['Vegetables', 'Onion'],
  },
  {
    id: '8',
    title: 'Hybrid Maize Seeds',
    price: '₹250/kg',
    quantity: '100 kg',
    image: 'https://images.unsplash.com/photo-1556909114-44e3e9399a2e?w=400',
    location: 'Hyderabad, Telangana',
    seller: 'Krishna Rao',
    categoryPath: ['Seeds', 'Crop Seeds'],
  },
  {
    id: '9',
    title: 'Holstein Friesian Cow',
    price: '₹65,000',
    quantity: '1 unit',
    image: 'https://images.unsplash.com/photo-1570042225831-d1fa3b4f4d4f?w=400',
    location: 'Anand, Gujarat',
    seller: 'Bharat Patel',
    categoryPath: ['Livestock', 'Cattle'],
  },
  {
    id: '10',
    title: 'Fresh Bananas',
    price: '₹40/dozen',
    quantity: '200 dozen',
    image: 'https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?w=400',
    location: 'Jalgaon, Maharashtra',
    seller: 'Ramesh Chaudhari',
    categoryPath: ['Fruits', 'Banana'],
    isNew: true,
  },
  {
    id: '11',
    title: 'Organic Compost Fertilizer',
    price: '₹15/kg',
    quantity: '1000 kg',
    image: 'https://images.unsplash.com/photo-1594992658473-3a93f3d4d616?w=400',
    location: 'Coimbatore, Tamil Nadu',
    seller: 'Murugan S',
    categoryPath: ['Fertilizers / Pesticides', 'Organic'],
    isNew: true,
  },
  {
    id: '12',
    title: 'Mini Tractor - 25 HP',
    price: '₹4,50,000',
    quantity: '1 unit',
    image: 'https://images.unsplash.com/photo-1605338803155-8b14f6f7d7c1?w=400',
    location: 'Ludhiana, Punjab',
    seller: 'Harjeet Brar',
    categoryPath: ['Tools / Equipment', 'Tractors'],
    isNew: true,
  },
]
