// Shared service-type metadata — single source of truth for the services
// module (browse page, offer form, detail page, my-services). Keys must
// match SERVICE_TYPES in backend/src/services/dto/service.dto.ts.
import {
  HardHat, Tractor, Car, Cog, GraduationCap, Stethoscope, PawPrint, Zap, Cpu,
  HeartPulse, ShieldAlert, Droplets, Paintbrush, Wrench, Hammer, ChefHat, Tent,
  Droplet, Milk, Heart, Recycle, Sprout, BookOpen, Shirt, Snowflake, Flame,
  Scissors, Brush, ShowerHead, ShieldCheck, WashingMachine, Container, Leaf,
  Layers, CarFront, Ambulance, FileSignature, Landmark, Truck, Briefcase,
  Flower2, Hand, BedDouble, Candy, Utensils, Building2, UtensilsCrossed, Camera,
  Music, ClipboardList, Cake, Armchair, Music2, Drum, PencilRuler, Construction, Sofa,
  Sparkles,
} from 'lucide-react'

export const SERVICE_TYPE_META = {
  labour:              { icon: HardHat,        en: 'Labour',                      hi: 'मज़दूर' },
  machinery:           { icon: Tractor,        en: 'Machinery',                   hi: 'मशीनरी' },
  machinery_driver:    { icon: Car,            en: 'Machinery Driver',            hi: 'मशीन ड्राइवर' },
  machine_operator:    { icon: Cog,            en: 'Machine Operator',            hi: 'मशीन ऑपरेटर' },
  tutor:               { icon: GraduationCap,  en: 'Tutor',                       hi: 'ट्यूटर' },
  doctor:              { icon: Stethoscope,    en: 'Doctor',                      hi: 'डॉक्टर' },
  veterinary:          { icon: PawPrint,       en: 'Veterinarian',                hi: 'पशु चिकित्सक' },
  electrician:         { icon: Zap,            en: 'Electrician',                 hi: 'इलेक्ट्रीशियन' },
  technician:          { icon: Cpu,            en: 'Technician',                  hi: 'तकनीशियन' },
  nursing_attendant:   { icon: HeartPulse,     en: 'Nursing Attendant',           hi: 'नर्सिंग परिचारक' },
  snake_catcher:       { icon: ShieldAlert,    en: 'Snake Catcher',               hi: 'साँप पकड़ने वाला' },
  plumber:             { icon: Droplets,       en: 'Plumber',                     hi: 'प्लंबर' },
  car_painter:         { icon: Paintbrush,     en: 'Car Painter',                 hi: 'कार पेंटर' },
  motor_mechanic:      { icon: Wrench,         en: 'Motor Mechanic',              hi: 'मोटर मैकेनिक' },
  mason:               { icon: Hammer,         en: 'Mason (Raj Mistry)',          hi: 'राज मिस्त्री' },
  cook:                { icon: ChefHat,        en: 'Cook / Chef',                 hi: 'रसोइया' },
  tent_service:        { icon: Tent,           en: 'Tent & Event Service',        hi: 'टेंट सेवा' },
  ro_water_service:    { icon: Droplet,        en: 'RO Water Purifier Service',   hi: 'आरओ वॉटर सर्विस' },
  milkman:             { icon: Milk,           en: 'Milkman / Dairy Supplier',    hi: 'दूधवाला' },
  blood_donor:         { icon: Heart,          en: 'Blood Donor',                 hi: 'रक्तदाता' },
  scrap_dealer:        { icon: Recycle,        en: 'Scrap Dealer (Kabadiwala)',   hi: 'कबाड़ीवाला' },
  plant_nursery:       { icon: Sprout,         en: 'Plant Nursery',               hi: 'नर्सरी' },
  priest:              { icon: BookOpen,       en: 'Priest / Pandit',             hi: 'पंडित / पुरोहित' },
  dry_cleaner:         { icon: Shirt,          en: 'Dry Cleaner',                 hi: 'ड्राई क्लीनर' },
  ac_fridge_service:   { icon: Snowflake,      en: 'AC & Refrigerator Service',   hi: 'एसी / फ्रिज सर्विस' },
  tyre_welding:        { icon: Flame,          en: 'Tyre Puncture & Welding',     hi: 'टायर पंचर व वेल्डिंग' },
  barber:              { icon: Scissors,       en: 'Barber',                      hi: 'नाई' },
  septic_tank_cleaner: { icon: Brush,          en: 'Septic Tank Cleaner',         hi: 'सेप्टिक टैंक सफाई' },
  pipe_fitter:         { icon: ShowerHead,     en: 'Water Pipe Fitter',           hi: 'वॉटर पाइप फिटर' },
  insurance_agent:     { icon: ShieldCheck,    en: 'Insurance Agent',             hi: 'बीमा एजेंट' },
  laundry:             { icon: WashingMachine, en: 'Laundry Service (Dhobi)',     hi: 'धोबी' },
  water_tank_cleaner:  { icon: Container,      en: 'Water Tank Cleaner',          hi: 'वॉटर टैंक क्लीनर' },
  gardener:            { icon: Leaf,           en: 'Gardener (Mali)',             hi: 'माली' },
  ironing_service:     { icon: Layers,         en: 'Ironing / Press Service',     hi: 'इस्त्री / प्रेस सेवा' },
  car_wash:            { icon: CarFront,       en: 'Car Wash',                    hi: 'कार वॉश' },
  ambulance:           { icon: Ambulance,      en: 'Ambulance Service',           hi: 'एम्बुलेंस' },
  decorator_florist:   { icon: Flower2,        en: 'Decorator / Florist',         hi: 'डेकोरेटर / फूल सज्जा' },
  mehendi_artist:      { icon: Hand,           en: 'Mehendi Artist',              hi: 'मेहंदी आर्टिस्ट' },
  bistar_house:        { icon: BedDouble,      en: 'Bedding & Linen Rental',      hi: 'बिस्तर हाउस' },
  halwai:              { icon: Candy,          en: 'Halwai (Sweet Maker)',        hi: 'हलवाई' },
  waiter:              { icon: Utensils,       en: 'Waiter / Serving Staff',      hi: 'वेटर / सर्विंग स्टाफ' },
  venue_provider:      { icon: Building2,      en: 'Venue Provider',              hi: 'वेन्यू प्रदाता' },
  caterer:             { icon: UtensilsCrossed,en: 'Caterer',                     hi: 'कैटरर' },
  photographer:        { icon: Camera,         en: 'Photographer & Videographer', hi: 'फोटोग्राफर व वीडियोग्राफर' },
  dj_sound:            { icon: Music,          en: 'DJ / Sound & Entertainment',  hi: 'डीजे / साउंड' },
  makeup_artist:       { icon: Sparkles,       en: 'Hair & Makeup Artist',        hi: 'हेयर व मेकअप आर्टिस्ट' },
  wedding_planner:     { icon: ClipboardList,  en: 'Wedding Planner / Coordinator', hi: 'वेडिंग प्लानर' },
  cake_supplier:       { icon: Cake,           en: 'Cake & Dessert Supplier',     hi: 'केक व मिठाई सप्लायर' },
  event_rental:        { icon: Armchair,       en: 'Event Rental Company',        hi: 'इवेंट रेंटल' },
  choreographer:       { icon: Music2,         en: 'Choreographer',               hi: 'कोरियोग्राफर' },
  dhol_musician:       { icon: Drum,           en: 'Dhol / Traditional Musicians', hi: 'ढोल / वाद्यवृंद' },
  architect:           { icon: PencilRuler,    en: 'Architect',                   hi: 'आर्किटेक्ट' },
  structural_engineer: { icon: Construction,   en: 'Structural Engineer',         hi: 'स्ट्रक्चरल इंजीनियर' },
  interior_designer:   { icon: Sofa,           en: 'Interior Designer',           hi: 'इंटीरियर डिज़ाइनर' },
  patwari:             { icon: FileSignature,  en: 'Patwari',                     hi: 'पटवारी' },
  loan_agent:          { icon: Landmark,       en: 'Loan / Subsidy Agent',        hi: 'लोन / सब्सिडी एजेंट' },
  transport:           { icon: Truck,          en: 'Transport',                   hi: 'ट्रांसपोर्ट' },
  other:               { icon: Briefcase,      en: 'Other',                       hi: 'अन्य' },
}

export const RATE_LABELS = {
  per_day:    { en: '/day',        hi: '/दिन' },
  per_hour:   { en: '/hr',         hi: '/घंटा' },
  per_acre:   { en: '/acre',       hi: '/एकड़' },
  per_visit:  { en: '/visit',      hi: '/विज़िट' },
  per_month:  { en: '/month',      hi: '/माह' },
  fixed:      { en: 'fixed',       hi: 'तय' },
  negotiable: { en: 'negotiable',  hi: 'बातचीत पर' },
}

export const RATE_UNITS = [
  { v: 'per_day',    en: 'per day',     hi: 'प्रति दिन' },
  { v: 'per_hour',   en: 'per hour',    hi: 'प्रति घंटा' },
  { v: 'per_acre',   en: 'per acre',    hi: 'प्रति एकड़' },
  { v: 'per_visit',  en: 'per visit',   hi: 'प्रति विज़िट' },
  { v: 'per_month',  en: 'per month',   hi: 'प्रति माह' },
  { v: 'fixed',      en: 'fixed price', hi: 'तय कीमत' },
  { v: 'negotiable', en: 'negotiable',  hi: 'बातचीत पर' },
]
